language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email: false
